### ISSUE TITLE
Flagged URLs in the Control Panel don't open

### ISSUE THREAD

**Issue by noor8380** [mithra62/flag-master#3]
When the flagged urls are clicked in the control panel, they result in a white page.

Am using EE 2.11.3 with the latest Flag Master.

Any help is appreciated.

**Comment by eric-lamb62** [comment]
White page is likely due to your PHP error settings. Enable error output and post the error here and I'm sure it'll make sense.

**Comment by noor8380** [comment]
Thank you for your reply.

The following is the error message:

Fatal error: Call to a member function get_entry() on a non-object in /html/system/expressionengine/third_party/flag_master/mcp.flag_master.php on line 445

A PHP Error was encountered
Severity: Notice
Message: Undefined property: Addons_modules::$channel_data
Filename: flag_master/mcp.flag_master.php
Line Number: 445

**Comment by noor8380** [comment]
Guess there was a similar question here
https://devot-ee.com/add-ons/support/ct-admin/viewthread/9477/P15

**Comment by noor8380** [comment]
Hello Eric,

Thank you for your reply.

The following is the error:

A PHP Error was encountered

Severity: Notice

Message: Undefined property: Addons_modules::$channel_data

Filename: flag_master/mcp.flag_master.php

Line Number: 445

*Fatal error*: Call to a member function get_entry() on a non-object in
*/html/system/expressionengine/third_party/flag_master/mcp.flag_master.php* on
line *445*


I had recently bought the Securit-ee and it is awesome.

Do you have a discount on Backup Pro?



Thank You,

Best Regards,
Noor Mohammad.
Mobile: +965 6595 8323

**Comment by eric-lamb62** [comment]
Ok, the master branch has been updated with the fix for this. Can you confirm?

**Comment by noor8380** [comment]
Hello Eric,

The new update fixed the issue.
Thank you for your prompt response and fix :)
